#!/usr/bin/python3
from enum import Enum


class Command(Enum):
    """
    A class containing commands for switching on/off the monitoring and data storage..
    ...

    Attributes
    ----------
    START : str
        Start monitoring.

    SHUTDOWN : str
        Stop monitoring.

    START_STORE : str
        Start storing the events generated by the monitoring.

    STOP_STORE : str
        Stop storing the events generated by the monitoring.
    """
    START = 'activate'
    SHUTDOWN = 'shutdown'
    START_STORE = 'start_store'
    STOP_STORE = 'stop_store'


class ResponseCode(Enum):
    """
    A class containing response codes returned by the monitoring or data storage.
    ...

    Attributes
    ----------
    SUCCESS : str,
        The command was executed successfully.

    FAILURE : str,
        The execution of the command ended up with an error.
    """
    SUCCESS = 200
    FAILURE = 400


class MessageType(Enum):
    """
    A class containing types of the messages used for communication with the monitoring.
    ...

    Attributes
    ----------
    RESPONSE : str
        The message is of type response.

    REQUEST : str
        The message is of type request.

    INFO : str
        The message is of type info.
    """
    RESPONSE = 'response'
    REQUEST = 'request'
    INFO = 'info'
